<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>instanto-teavm-pom</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath/>
  </parent>
  <groupId>io.instanto.fixture</groupId>
  <artifactId>teavm-consumer</artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
    <fixture.outputDirectory>${project.build.directory}/teavm</fixture.outputDirectory>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso-apis</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.teavm</groupId>
        <artifactId>teavm-maven-plugin</artifactId>
        <configuration>
          <mainClass>example.SynchronousApplication</mainClass>
          <targetType>JAVASCRIPT</targetType>
          <targetDirectory>${fixture.outputDirectory}</targetDirectory>
          <targetFileName>app.mjs</targetFileName>
          <jsModuleType>ES2015</jsModuleType>
          <optimizationLevel>ADVANCED</optimizationLevel>
          <minifying>true</minifying>
        </configuration>
        <executions>
          <execution>
            <goals><goal>compile</goal></goals>
            <phase>prepare-package</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>extensions</id>
      <dependencies>
        <dependency>
          <groupId>io.instanto</groupId>
          <artifactId>instanto-teavm-extensions</artifactId>
          <scope>provided</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
